### ISSUE TITLE
CMU15-721 Advanced Database Systems (Spring 2019)

### ISSUE THREAD

**Issue by shaqsnake** [wenhan-wu/OpenCourseCatalog#1]
Hi，CMU最新一期的高级数据库系统课程已经发布一大半了，麻烦Up主后续更新一下吧。

[课程主页](https://15721.courses.cs.cmu.edu/spring2019/)
[Youtube页面](https://www.youtube.com/playlist?list=PLSE8ODhjZXja7K1hjZ01UTVDnGQdx5v5U)

**Comment by elder-frog** [comment]
OK

**Comment by elder-frog** [comment]
已搬运，av50204001
