### ISSUE TITLE
亲爱的up主，台湾大学微积分一，还有百度云的链接么?

### ISSUE THREAD

**Issue by wangjialiang5589** [wenhan-wu/OpenCourseCatalog#2]
亲爱的up主，台湾大学微积分一，还有百度云的链接么?刚看几集就没了........

**Comment by elder-frog** [comment]
过段时间上传到百度云，链接我会挂在淘宝

**Comment by elder-frog** [comment]
已上传，https://item.taobao.com/item.htm?id=592620650978
