### ISSUE TITLE
求网易上缺失的UCI organic chemistry 51B David Van Vranken教授讲授的几个视频

### ISSUE THREAD

**Issue by tracy-Lu** [wenhan-wu/OpenCourseCatalog#24]
第 5 节: 【醇、醚和环氧化物（第四部分） 】
第 6 节: 【烯（第一部分） 】
第 15 节: 【Reduction and Oxidation, Part 3 】
第 16 节: 【Infrared Spectroscopy 】
第20节： radicals
第 23 节: 【Aromaticity 】
第 24 节: 【Electrophilic Aromatic Substitution 】
第 25 节: 【Electrophilic Aromatic Substitution Part 2 】
第 26 节: 【Electrophilic Aromatic Substitution, Part 3 】

**Comment by tracy-Lu** [comment]
http://ocw.uci.edu/openchem/chem51b.html
是David Van Vranken博士的，不知道为什么网易公开课上，有这么多节课程视频缺失。

**Comment by elder-frog** [comment]
我过段时间搬运哈

**Comment by tracy-Lu** [comment]
好的，谢谢！非常感谢！

**Comment by elder-frog** [comment]
搬过了
https://www.bilibili.com/video/BV1ib411L7vV/
