### ISSUE TITLE
wow！amazing

### ISSUE THREAD

**Issue by Ilikeyou3000** [wenhan-wu/OpenCourseCatalog#25]
陶哲轩要开讲傅里叶分析了，搬过来瞅一下？

**Comment by elder-frog** [comment]
过几天去找找视频，最近比较忙

**Comment by elder-frog** [comment]
> Video Recording: Lectures are recorded and placed on the CCLE web site.  In particular, be advised that any audio, video, or text you share in the lecture may end up in the recording.  UCLA privacy policies prohibit these recordings from being made available to non-UCLA participants.
