### ISSUE TITLE
UCI open chemistry

### ISSUE THREAD

**Issue by nbmy7788** [wenhan-wu/OpenCourseCatalog#26]
up你好, 从 B站你上传的 UCI chem51系列过来的.
不知道能否再搬运几个open chemistry(http://ocw.uci.edu/collections/open_chemistry.html) 上面的课程?如:
Chem 107: Inorganic Chemistry, 
Chem 125: Advanced Organic Chemistry
Chem 131A. Quantum Principles
Chem 131B: Molecular Structure and Elementary Statistical Mechanics
Chem 203: Organic Spectroscopy
视频是放在YouTube上的.
谢谢!

**Comment by elder-frog** [comment]
好的，过段时间搬，最近很忙

**Comment by nbmy7788** [comment]
好的 谢谢!

**Comment by elder-frog** [comment]
已搬完
[[UCI] 加州大学尔湾分校 化学开放课程系列 (Open Chemistry)](https://www.bilibili.com/read/cv6539593)
