### ISSUE TITLE
A 2020 Vision of Linear Algebra

### ISSUE THREAD

**Issue by sufumin** [wenhan-wu/OpenCourseCatalog#27]
https://ocw.mit.edu/resources/res-18-010-a-2020-vision-of-linear-algebra-spring-2020/index.htm
MIT教授Gilbert Strang最新线性代数课程，持续更新中。
由于b站那版太久啦（_转眼老了十岁😭_）+录音录像质量不高，又恰逢去年五道口改用老爷子的原版书，希望能够搬运。

**Comment by elder-frog** [comment]
b站有
