### ISSUE TITLE
up求搬运上交量子力学与统计力学课程

### ISSUE THREAD

**Issue by qwqerwq** [wenhan-wu/OpenCourseCatalog#3]
http://cc.sjtu.edu.cn/G2S/site/preview#/rich/v/125288?ref=&currentoc=7488
课程链接如上

**Comment by elder-frog** [comment]
👌

**Comment by XIe-Yibin** [comment]
机器学习 AI系列

**Comment by elder-frog** [comment]
> 机器学习 AI系列

请详细说明课程名称或给出课程链接

**Comment by elder-frog** [comment]
已搬运 https://www.bilibili.com/video/av51954299/
