### ISSUE TITLE
希望能够搬运一下 MIT 18.05 Introduction to Probability and Statistics. 

### ISSUE THREAD

**Issue by Syuru727** [wenhan-wu/OpenCourseCatalog#30]
希望能够搬运一下 MIT 18.05 Introduction to Probability and Statistics. 主要是缺课程视频~
Thanks♪(･ω･)ﾉ

**Comment by elder-frog** [comment]
18.05 没有视频，看 UCI 的 [MATH 131A](https://www.youtube.com/playlist?list=PLqOZ6FD_RQ7n6XnvxxsWfxFtYf0Xj479J) 吧
