### ISSUE TITLE
请搬运下ocw的Applied Category Theory. 具体见下边

### ISSUE THREAD

**Issue by Malik-Wang** [wenhan-wu/OpenCourseCatalog#31]
也就是下方链接里的7个lecture. 
https://ocw.mit.edu/courses/mathematics/18-s097-applied-category-theory-january-iap-2019/lecture-videos-and-readings/index.htm

**Comment by elder-frog** [comment]
撞车 [Applied Category Theory（2019）](https://www.bilibili.com/video/BV1gE411i7ZB)
