### ISSUE TITLE
[TFY4345] Classical Mechanics on Youtube

### ISSUE THREAD

**Issue by liuyx3399** [wenhan-wu/OpenCourseCatalog#4]
https://www.youtube.com/playlist?list=PLUHTGp7T4Zn_FU64InC0C8ZsejaxMtO3s
Classical Mechanics by Jacob Linder NTYU
up主你好，这个经典力学的课B站上没有，还麻烦帮忙搬运一下，十分感谢~

**Comment by elder-frog** [comment]
好的

**Comment by liuyx3399** [comment]
up主，请问这个经典力学的课怎么还没有，是不是忘了呀

**Comment by elder-frog** [comment]
最近忙，再等等

**Comment by liuyx3399** [comment]
恩Ok:)

**Comment by elder-frog** [comment]
https://www.bilibili.com/video/av59839869/
