### ISSUE TITLE
MIT Walter

### ISSUE THREAD

**Issue by wangantian** [wenhan-wu/OpenCourseCatalog#5]
8.01 X, 8.02X 8.03  MIT help session
https://www.youtube.com/channel/UCiEHVhv0SBMpP75JbzJShqw/playlists

**Comment by wenhan-wu** [comment]
[MIT 8.01x 物理I：经典力学 答疑与习题讲解 (MIT 8.01x Help Sessions)](https://www.bilibili.com/video/av68948340)
[MIT 8.02x 物理II：电和磁 答疑与习题讲解 (MIT 8.02x Help Sessions)](https://www.bilibili.com/video/av68983905)

**Comment by elder-frog** [comment]
> 8.01 X, 8.02X 8.03 MIT help session
> https://www.youtube.com/channel/UCiEHVhv0SBMpP75JbzJShqw/playlists

[MIT 8.01x 物理I：经典力学 答疑与习题讲解 (MIT 8.01x Help Sessions)](https://www.bilibili.com/video/av68948340)
[MIT 8.02x 物理II：电和磁 答疑与习题讲解 (MIT 8.02x Help Sessions)](https://www.bilibili.com/video/av68983905)

**Comment by elder-frog** [comment]
[MIT 8.03x 物理 III：振动与波 答疑与习题讲解](https://www.bilibili.com/video/av70580345/)
