### ISSUE TITLE
求课程

### ISSUE THREAD

**Issue by GuangqingWang** [wenhan-wu/OpenCourseCatalog#6]
求学似若渴, 迷失于网海.
止步而不前, 绝望于深渊.
遇楼主偶然, 如深夜得光.
寄予以厚望, 求课程如下.
偏微分算子 微局部分析.
念机缘使然, 望不吝分享.

**Comment by elder-frog** [comment]
我抽时间看一下，最近几个月太忙了。。。。

**Comment by GuangqingWang** [comment]
多谢楼主，感谢楼主在百忙之中帮俺一把。
课程的英文名字分别是 pseudo-differential operators；Microlocal analysis；若果不麻烦，相关的课程楼主顺道搬过来呗

**Comment by GuangqingWang** [comment]
> 我抽时间看一下，最近几个月太忙了。。。。

多谢楼主，感谢楼主在百忙之中帮俺一把。
课程的英文名字分别是 pseudo-differential operators；Microlocal analysis；若果不麻烦，相关的课程楼主顺道搬过来呗

**Comment by elder-frog** [comment]
好的，最近开始搬

**Comment by elder-frog** [comment]
[MSRI Introductory Workshop: Microlocal Analysis](https://www.msri.org/workshops/897)

**Comment by elder-frog** [comment]
https://www.bilibili.com/video/av90400530/
