### ISSUE TITLE
求Coursera最热课程

### ISSUE THREAD

**Issue by fahawifi** [wenhan-wu/OpenCourseCatalog#7]
[https://www.mooc.cn/specialization](https://www.mooc.cn/specialization)
1[.Java编程和软件工程基础](https://www.coursera.org/specializations/java-programming?ranMID=40328&ranEAID=zMHlqgkeyKQ&ranSiteID=zMHlqgkeyKQ-cnWyAkVf5NwUvmcpn9pFgw&siteID=zMHlqgkeyKQ-cnWyAkVf5NwUvmcpn9pFgw&utm_content=10&utm_medium=partners&utm_source=linkshare&utm_campaign=zMHlqgkeyKQ)Java Programming and Software Engineering Fundamentals

2.[Android 应用程序开发专项课程](https://www.coursera.org/specializations/android-app-development?ranMID=40328&ranEAID=zMHlqgkeyKQ&ranSiteID=zMHlqgkeyKQ-zxC3ppKcirtACUvX90lN.Q&siteID=zMHlqgkeyKQ-zxC3ppKcirtACUvX90lN.Q&utm_content=10&utm_medium=partners&utm_source=linkshare&utm_campaign=zMHlqgkeyKQ)Android App Development

3.[创业能力：把你的想法变成有形企业专项课程](https://www.coursera.org/specializations/wharton-entrepreneurship?ranMID=40328&ranEAID=zMHlqgkeyKQ&ranSiteID=zMHlqgkeyKQ-BBT4uKuNMVWOOaWSRjvZ.w&siteID=zMHlqgkeyKQ-BBT4uKuNMVWOOaWSRjvZ.w&utm_content=10&utm_medium=partners&utm_source=linkshare&utm_campaign=zMHlqgkeyKQ)
Entrepreneurship

4.深度学习专项课程
[Deep Learning](https://www.coursera.org/specializations/deep-learning?ranMID=40328&ranEAID=zMHlqgkeyKQ&ranSiteID=zMHlqgkeyKQ-IbrkCPBIoqKb5GUqbcrIqg&siteID=zMHlqgkeyKQ-IbrkCPBIoqKb5GUqbcrIqg&utm_content=10&utm_medium=partners&utm_source=linkshare&utm_campaign=zMHlqgkeyKQ)

**Comment by elder-frog** [comment]
这些专项课程暂时没有办法搬运，无下载权限
