### ISSUE TITLE
求GIS（地理信息科学），RS(遥感）课程

### ISSUE THREAD

**Issue by hy47** [wenhan-wu/OpenCourseCatalog#9]
- 具体的名称我也不知道，这个课程可能比较小众，相关的都可以。

- 如果有时间的希望多搬运一些计算机编程、人工智能，大数据之类的视频，谢谢了。

**Comment by elder-frog** [comment]
人工智能，大数据之类课程已经有很多，建议自行CS231，CS224等
GIS（地理信息科学），RS(遥感）这些我要找一找

**Comment by Kiwamm** [comment]
老哥，自行cs231，cs224是啥意思啊，萌新不懂，我刚好也是学大数据的

**Comment by elder-frog** [comment]
> 老哥，自行cs231，cs224是啥意思啊，萌新不懂，我刚好也是学大数据的

Stanford 课程编号
